#lang racket
(provide SIZE)
(provide MARGIN)
(provide PADDING)
(provide CYCLE-MARGIN)
(provide MAX-CONTENT)
(provide ARROW-HEAD-SIZE)
(provide ARROW-ROOT-RADIUS)

(define SIZE 40)
(define MARGIN (+ 20 SIZE))
(define PADDING (/ SIZE 3))
(define CYCLE-MARGIN 10)
(define MAX-CONTENT 3)
(define ARROW-HEAD-SIZE 6)
(define ARROW-ROOT-RADIUS 2)